// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCkIc98Ya3wdpup-D1dv3-h6Fn8lowWH8Q',
    appId: '1:886229230705:web:0a9b369ee60460387d27d0',
    messagingSenderId: '886229230705',
    projectId: 'taskmaster-pro-e66a3',
    authDomain: 'taskmaster-pro-e66a3.firebaseapp.com',
    storageBucket: 'taskmaster-pro-e66a3.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA9-V3yZ0j3_ilijZx1sWf7mUNnQSzB1nE',
    appId: '1:886229230705:android:dc3c1892fbf5ca1e7d27d0',
    messagingSenderId: '886229230705',
    projectId: 'taskmaster-pro-e66a3',
    storageBucket: 'taskmaster-pro-e66a3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCl0kaw2o1jCrpdA4tTNqvSbI3hCpBzRj8',
    appId: '1:886229230705:ios:06645b886c193d617d27d0',
    messagingSenderId: '886229230705',
    projectId: 'taskmaster-pro-e66a3',
    storageBucket: 'taskmaster-pro-e66a3.firebasestorage.app',
    iosBundleId: 'com.coboy.taskMaster',
  );
}
